
console.log(firstName, lastName, country, city, age, isMarried) 
console.log(gravity, boilingPoint, PI) 
console.log(name, job, live)
console.log(typeof firstName)
console.log(typeof lastName)
console.log(typeof country)
console.log(typeof city)
console.log(typeof age)
console.log(typeof isMarried)
